# Generated by Django 4.2.4 on 2023-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulses',
            name='product_name',
            field=models.CharField(blank=True, default='Missing', max_length=255, null=True),
        ),
    ]
