# Generated by Django 4.2.4 on 2023-08-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_integrations', '0003_alter_impulses_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulses',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
