# Generated by Django 4.2.4 on 2023-08-28 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine_integrations', '0006_alter_machine_machine_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Machine',
            new_name='Machines',
        ),
    ]
