# Generated by Django 4.2.4 on 2023-10-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine_integrations', '0007_rename_machine_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impulses',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='impulses',
            name='sensor_counter',
            field=models.IntegerField(db_index=True),
        ),
    ]
